format_version: 10
pipelines:
  release:
    group: defaultGroup
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-d6b1e38:
        git: https://github.com/derva/gocd_test
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
    - packing:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          packing-tests:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - Packing tests
                command: echo
                run_if: passed
  build:
    group: defaultGroup
    label_template: ${COUNT}
    dispaly_order: -1
    parameters:
      param1: ''
    materials:
      mygit:
        git: https://github.com/derva/gocd_test
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
      - build: #stage one
          jobs:
            Novi:
              tasks:
                - exec:
                    arguments:
                    command: build.sh
                    run_if: passed
                
